module.exports = [
    "“I’m sorry” and “I apologize” mean the same thing... except when you’re at a funeral.",
    "A boy says to his mother, \"Mom, why is it everyone in our family dies so young?\"\n ⇒ \n\"Mother?\"\n\n\n\"Mother?\"",
    "A boy says to his mother, \"Mom, why is it everyone in our family dies so young?\"\n ⇒ \n\"Mother?\"\n\n\n\"Mother?\"",
    "A boy says to his mother, \"Mom, why is it everyone in our family dies so young?\"\n ⇒ \n\"Mother?\"\n\n\n\"Mother?\"",
    "A doe walks out of the woods, \"That’s the last time I do that for two bucks.\"",
    "A horse walked into a bar. Several people got up and left as they spotted the potential danger in the situation.",
    "A man falls from the rooftop of a 60 story building. People on the 30th floor hear him falling, \"So faaaaar so gooooood!\"",
    "A man goes into a confessional and says, \"Father, I've done something terrible. I've murdered a man. And I have these horrible thoughts. I want to kill so many more people. I don't know if I can stop myself. What should I do?\"\nThe priest says, \"My son, the punishment for killing one of Gods children is eternal damnation. You'd be a fool to stop now.\"",
    "A man walks into a bar and ask for a beer.\nThe bartender is a horse but pours one anyway.\nThe man says, \"This isn’t a beer,\" and promptly wakes up in a cold sweat, staring into the loveless eyes of his partner, who has been watching him sleep with a knife raised over his head.\nThe man jolts awake a second time and finds himself back in the bar, holding the glass of liquid.\n\"Well, I’ll drink it anyway.\"\nThe horse says nothing.\n ⇒ That isn’t a joke; it’s your fortune.",
    "A mouse and an elephant are walking across a bridge. The mouse turns to the elephant and says, \"We make a lot of noise.\"",
    "A red ball says to a blue ball, \"I can bounce higher than you!\" The blue ball just sits in silence because it’s an inanimate object with no mouth.",
    "A woman walked into a bar and asked the bartender for a double entendre. So the bartender gave it to her.",
    "Asked My Date To Meet Me At The Gym, But She Never Showed Up...\n ⇒ Guess the two of us aren’t going to work out",
    "Atom walks into a bar. The bartender tells him to split. Everyone dies.",
    "Before surgery, my anesthesiologist offered to put me under with gas or a boat paddle.\n ⇒ It was an ether/oar situation.",
    "Did you hear about the new corduroy pillows?\n ⇒  They’re making headlines everywhere!",
    "git commit -m \"fix typeo\"",
    "git commit -m \"once more with feeling\"",
    "git commit -m \"synergizing backward overflow for upward mobility\"",
    "Got arrested at the airport. Apparently, security doesn’t appreciate it when you call \"shotgun\" before boarding a plane.",
    "Hammer walks into a bar. Bartender asks him how work went today. \"Nailed it!\"",
    "I farted on the elevator.\n ⇒ It was wrong on so many levels.",
    "I have a Heisenberg joke but I don't know how long it takes",
    "I have a Schrödinger joke. It's funny and it's not.",
    "I have a Zeno's paradox joke but I can never get to the end",
    "I once made a belt out of wrist watches; `it was a complete waist of time.",
    "I started a band called 999 Megabytes — we don’t have a gig yet.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "I used to be addicted to soap, but I'm clean now.",
    "I used to think the brain was the most important organ.\n ⇒  Then I thought, \"Look what’s telling me that!\"",
    "I wish I could love unicorns, but love isn’t real.",
    "I wondered why the baseball was getting bigger. Then it hit me.",
    "I’ve lost my thesaurus. I can’t find the words to describe how upsetting this is.",
    "If I’ve told you once, I’ve told you a million times: Don’t exaggerate!",
    "Is there another word for synonym?",
    "It’s hard to explain puns to kleptomaniacs because they always take things, literally.",
    "Man, I spent a long time at the Gym this morning.\n ⇒ We’ve started calling the bathroom \"the Gym\".",
    "My friend couldn't afford to pay his water bill.\n ⇒ I sent him a \"Get Well Soon\" card",
    "My friend likes to impress girls by drawing detailed pictures of a Ford F-150.\n ⇒ He's a pickup artist.",
    "My wife is really mad at the fact that I have no sense of direction.\n ⇒ So I packed up my stuff and right.",
    "My wife screamed \"you haven't listened to a single word I've said, have you?!\"\n ⇒ What a weird way to start a conversation.",
    "Of all the inventions of the last 100 years, the dry erase board has to be the most remarkable.",
    "The oil excavators attempted in vain to clean up the spill.\nIt was crude.",
    "Two drunk guys were about to get into a fight. One draws a line in the dirt and says, “If you cross this line, I’ll hit you in the face.”\n ⇒ That was the punchline.",
    "What do you call a boomerang that won't come back? A stick.",
    "What is red and smells like blue paint?\n ⇒ Red paint.",
    "What’s green and has wheels? Grass. I lied about the wheels.",
    "Whoever put the letter ’b’ in the word ’subtle’ deserves a pat on the back.",
    "Whose cruel idea was it for the word ’lisp’ to have an ’s’ in it?",
    "Why is there no other word for thesaurus?",
    "Why was six afraid of seven? It wasn’t. Numbers aren’t sentient and thus incapable of feeling fear.",
    "You know what you get when you cross a cow with an octopus?\n ⇒ A visit from the ethics committee and immediate withdrawal of your funding.",
    "You know what you get when you cross a rabbit with a rottweiler?\n ⇒ A rottweiler.",
    "You know why baby ducks walk so softly?\n ⇒ Because they can’t walk, hardly.",
    "You know why dinosours can’t talk?\n ⇒ because they’re dead.",
];